server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:notesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: none  
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator

logging:
  level:
    com.notepad.notesapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"